FROM bellsoft/liberica-openjdk-debian:17.0.2

ADD build/libs/scheduled-database-update-tool-0.0.1.jar /scheduled-database-update-tool-0.0.1.jar

CMD ["java", "-jar", "scheduled-database-update-tool-0.0.1.jar"]