cryptocurrency.ids: 80, 90, 48543
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/currencies_db
    username: postgres
    password: 1
    driverClassName: org.postgresql.Driver
